apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sql-case
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-case
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sql-case
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
      containers:
      - name: sql-case
        image: mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-18.04
        ports:
          - containerPort: 1400
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sa-password-case
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
        resources:
          limits:
            memory: "2Gi"
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: pvc-data-case