apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-sql-plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sql-plex
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - sqlserver
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
      containers:
      - name: sql-plex
        image: mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-18.04
        ports:
          - containerPort: 1400
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sa-password-plex
              key: SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
        resources:
          limits:
            memory: "4Gi"
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: pvc-data-plex